- hosts: crawler
  tasks:
  - name: remove git
    file:
      path: /root/ig/
      state: absent
  - name: git update
    git:
     repo: "https://github.com/ZhaoGuan/ig_crawler.git"
     dest: /root/ig/ig_crawler
  - name: update mysql_config
    copy:
      src: mysql_config.py
      remote_src : no
      dest: /root/ig/ig_crawler/ig_crawler/tools/mysql_config.py
      owner: root

  - name: update redis_config
    copy:
      src: redis_config.py
      remote_src : no
      dest: /root/ig/ig_crawler/ig_crawler/tools/redis_config.py
      owner: root